apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bare-metal-fulfillment-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "bare-metal-fulfillment-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "bare-metal-fulfillment-operator.selectorLabels" . | nindent 4 }}
