{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "bare-metal-fulfillment-operator.labels" . | nindent 4 }}
  name: {{ include "bare-metal-fulfillment-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
