# This rule is not used by the project bare-metal-fulfillment-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the osac.openshift.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bare-metal-fulfillment-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: baremetalpool-editor-role
rules:
- apiGroups:
  - osac.openshift.io
  resources:
  - baremetalpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osac.openshift.io
  resources:
  - baremetalpools/status
  verbs:
  - get
